# Generated by Django 6.0.5 on 2026-05-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL única para la invitación (ej: baby-shower-mateo)', unique=True)),
                ('titulo_landing', models.CharField(help_text='Ej: ¡Bienvenido Mateo!', max_length=200)),
                ('descripcion', models.TextField(help_text='Texto de bienvenida o dedicatoria')),
                ('fecha_evento', models.DateTimeField()),
                ('direccion_texto', models.CharField(help_text='Ej: Calle Falsa 123, Ciudad', max_length=255)),
                ('direccion_google_maps_link', models.URLField(help_text='Link directo para abrir en Google Maps')),
                ('link_lista_deseos', models.URLField(blank=True, help_text='Link a la mesa de regalos (opcional)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CapaParallax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Sube una imagen (idealmente PNG transparente para capas frontales)', upload_to='parallax/')),
                ('z_index', models.IntegerField(default=0, help_text='Posición Z de la capa (Ej: -5 para fondo, 0 medio, 5 frente). Determina la escala y el nivel de parallax.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en el que se renderiza (0 primero, 1 segundo...)')),
                ('invitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='invitaciones.invitacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
