# Generated by Django 6.0.5 on 2026-05-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='color_primario',
            field=models.CharField(default='#8b5cf6', help_text='Color para botones y acentos', max_length=7),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='color_texto',
            field=models.CharField(default='#ffffff', help_text='Color del texto principal', max_length=7),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='fuente_texto',
            field=models.CharField(choices=[('Inter', 'Inter (Limpio y Moderno)'), ('Playfair Display', 'Playfair Display (Elegante y Clásico)'), ('Nunito', 'Nunito (Redondeado y Amigable)'), ('Pacifico', 'Pacifico (Cursiva Juguetona)'), ('Cinzel', 'Cinzel (Sofisticado Serif)')], default='Inter', help_text='Tipografía para la invitación', max_length=50),
        ),
    ]
