# Generated by Django 6.0.5 on 2026-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0002_invitacion_color_primario_invitacion_color_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capaparallax',
            name='anclaje',
            field=models.CharField(choices=[('centro', 'Centro'), ('abajo', 'Abajo'), ('arriba', 'Arriba'), ('izquierda', 'Izquierda'), ('derecha', 'Derecha')], default='centro', help_text='A qué lado de la pantalla se pega la imagen', max_length=20),
        ),
        migrations.AddField(
            model_name='capaparallax',
            name='modo_escala',
            field=models.CharField(choices=[('cover', 'Cover (Llenar pantalla - Corta los bordes)'), ('contain', 'Contain (Ajustar al ancho - No se corta)')], default='cover', help_text='Estrategia de tamaño', max_length=20),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='activar_bokeh',
            field=models.BooleanField(default=False, help_text='Activar efecto cinematográfico de desenfoque de profundidad'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='fuerza_desplazamiento',
            field=models.FloatField(default=1.0, help_text='Multiplicador del deslizamiento (Ej: 1.0 normal, 2.0 agresivo)'),
        ),
        migrations.AddField(
            model_name='invitacion',
            name='fuerza_giro',
            field=models.FloatField(default=1.0, help_text='Multiplicador de la rotación 3D (Ej: 1.0 normal, 0.5 suave)'),
        ),
    ]
