# Generated by Django 6.0.5 on 2026-05-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0003_capaparallax_anclaje_capaparallax_modo_escala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capaparallax',
            name='anclaje',
        ),
        migrations.RemoveField(
            model_name='capaparallax',
            name='modo_escala',
        ),
        migrations.AddField(
            model_name='capaparallax',
            name='dispositivo',
            field=models.CharField(choices=[('todos', 'Ambos (Universal)'), ('movil', 'Solo Móvil (Vertical 9:16)'), ('escritorio', 'Solo Escritorio (Horizontal 16:9)')], default='todos', help_text='¿En qué pantallas debe mostrarse esta capa?', max_length=20),
        ),
        migrations.AddField(
            model_name='capaparallax',
            name='pegar_abajo',
            field=models.BooleanField(default=False, help_text='Si se activa, la imagen no volará hacia arriba con el giroscopio, ocultando el corte del borde inferior.'),
        ),
    ]
