# Generated by Django 6.0.5 on 2026-05-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0004_remove_capaparallax_anclaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacion',
            name='intensidad_vigneta',
            field=models.FloatField(default=0.5, help_text='Intensidad de la viñeta (0 = ninguna, 1 = máxima)'),
        ),
    ]
