# Generated by Django 6.0.5 on 2026-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0005_invitacion_intensidad_vigneta'),
    ]

    operations = [
        migrations.AddField(
            model_name='capaparallax',
            name='es_sujeto_foco',
            field=models.BooleanField(default=False, help_text='Marca esta capa como el sujeto principal. El desenfoque Bokeh se calibrará para mantenerla 100% nítida.'),
        ),
    ]
